---
- name: "openSUSE: Add repository for buildbot packages"
  become: yes
  zypper_repository:
    name: "illuusio:/python"
    repo: "https://download.opensuse.org/repositories/home:/illuusio:/python/openSUSE_Leap_15.2/"
    auto_import_keys: yes
  tags: root

- name: "openSUSE: Install buildbot worker package"
  become: yes
  zypper:
    state: present
    name:
      - python3-buildbot_worker
      - python3-service_identity
  tags: root
