---
#
# Manage ssh keys for gerrit integration.
#
- name: "Create ssh directory."
  file:
    state: directory
    path: ".ssh"
    mode: "0700"

- name: "Install ssh keys for gerrit event streaming."
  copy:
    src: "{{ item.src }}"
    dest: ".ssh/{{ item.src | basename }}"
    mode: "{{ item.mode }}"
  loop:
    - src: "{{ buildbot_master_gerrit_ident }}"
      mode: "0600"
    - src: "{{ buildbot_master_gerrit_ident }}.pub"
      mode: "0644"

- name: "Add gerrit.openafs.org entry to known_hosts."
  known_hosts:
    name: "[gerrit.openafs.org]:29418"
    key: "{{ lookup('file', buildbot_master_gerrit_hostkey) }}"
  when:
    - buildbot_master_gerrit_hostkey is defined
    - buildbot_master_gerrit_hostkey | length > 0

# The old gerrit key is dsa encrypted so requires a config
# change to be permitted on modern systems.
- name: "Get ssh client version."
  command: ssh -V
  check_mode: no
  changed_when: false
  register: ssh_version

- name: "Trace ssh_version"
  debug:
    var: ssh_version.stderr

- name: "Permit DSA ssh keys."
  lineinfile:
    state: present
    path: ".ssh/config"
    line: "PubkeyAcceptedKeyTypes=+ssh-dss"
    create: yes
    mode: "0600"
  when: ssh_version.stderr.split(',')[0] is version('OpenSSH_7', 'ge')
